sudo: false
dist: trusty

language: node_js
node_js: "10"

script:
  - npm test

deploy:
  # Make a commit and a tag if an update was found.
  - provider: script
    script: node scripts/push.js
    skip_cleanup: true
    on:
      branch: master
  # Publish on tags.
  - provider: npm
    email: "star.ctor+bot@gmail.com"
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
